# Generated by Django 4.0.6 on 2022-08-28 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pesonal_account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='db_user',
            options={'verbose_name': 'Личный кабинет каждого пользователя', 'verbose_name_plural': 'Личный кабинет каждого пользователя'},
        ),
        migrations.AlterField(
            model_name='db_user',
            name='email_user',
            field=models.CharField(max_length=50, null=True, verbose_name='Почта'),
        ),
        migrations.AlterField(
            model_name='db_user',
            name='first_name',
            field=models.CharField(max_length=50, null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='db_user',
            name='phone_user',
            field=models.CharField(max_length=50, null=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='db_user',
            name='second_name',
            field=models.CharField(max_length=50, null=True, verbose_name='Фамилия'),
        ),
    ]
