# Generated by Django 4.0.6 on 2022-08-26 12:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pesonal_account', '0002_alter_db_user_options_alter_db_user_email_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='db_user',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
