# Generated by Django 4.0.6 on 2022-08-28 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_service',
        ),
        migrations.AddField(
            model_name='order',
            name='order_city',
            field=models.CharField(default=1, max_length=50, verbose_name='Город'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='order_country',
            field=models.CharField(default=2, max_length=50, verbose_name='Страна'),
            preserve_default=False,
        ),
    ]
